export const ORIENTATION_NUMBER = {
  0: 'PORTRAIT',
  1: 'PORTRAIT',
  2: 'PORTRAIT',
  3: 'LANDSCAPE',
  4: 'LANDSCAPE',
};

export const ORIENTATION = {
  PORTRAIT: 'PORTRAIT',
  LANDSCAPE: 'LANDSCAPE',
};
